apiVersion: v1
kind: Service
metadata:
  name: ado-webserver
  labels:
    app: ado-webserver
spec:
  ports:
  - name: web
    port: 8080
    targetPort: web
    protocol: TCP
  selector:
    app: ado-webserver